version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
  redis:
    image: redis:4-alpine
    networks:
      - backend
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
networks:
  frontend:
  backend:
